"use client";

import React, { useState, useEffect } from "react";
import { useRouter } from "next/navigation";
import { API_BASE, logoutUser } from "@/utils/api";
import { useAccessibility } from "@/context/AccessibilityContext";
import { Shield, LogOut, CheckCircle, AlertTriangle, Clock, MapPin, User, ChevronRight, CheckSquare, Bell, RefreshCw, Cpu, Activity } from "lucide-react";
import { playBeep, playSuccess, playWarning } from "@/utils/audio";

interface Task {
  id: string;
  agent: string;
  title: string;
  description: string;
  priority: "HIGH" | "MEDIUM" | "LOW";
  eta: string;
  location: string;
  status: "pending" | "completed";
}

export default function VolunteerPortal() {
  const router = useRouter();
  const { speakText, activeLanguage } = useAccessibility();

  const [token, setToken] = useState<string | null>(null);
  const [email, setEmail] = useState<string | null>(null);
  const [selectedRole, setSelectedRole] = useState<string>("Gate Management");
  const [isClient, setIsClient] = useState(false);
  const [loading, setLoading] = useState(false);

  const [tasks, setTasks] = useState<Task[]>([
    {
      id: "T1",
      agent: "Gate AI",
      title: "Direct flow to Gate C2 turnstiles",
      description: "Redirect backlog queue of 328 fans from Gate C to the adjacent Gate C2 turnstile pathway.",
      priority: "HIGH",
      eta: "2 min",
      location: "Gate C Sector",
      status: "pending"
    },
    {
      id: "T2",
      agent: "Cleaning AI",
      title: "Waste bin overflow resolution",
      description: "Bin Section 102 capacity is currently at 94%. Clear debris and deploy clean recycle liners.",
      priority: "HIGH",
      eta: "5 min",
      location: "Concourse Sect 102",
      status: "pending"
    },
    {
      id: "T3",
      agent: "Medical AI",
      title: "Deliver ice pack to first aid unit",
      description: "Medical Bay requires additional ice packs for minor heat hydration checkup at Seat A-102.",
      priority: "MEDIUM",
      eta: "4 min",
      location: "North Medical Bay",
      status: "pending"
    },
    {
      id: "T4",
      agent: "Accessibility AI",
      title: "Assisted wheelchair guide request",
      description: "Accompany visitor Somashekhar from accessible Parking Lot B to designated wheelchair stand A-102.",
      priority: "HIGH",
      eta: "3 min",
      location: "Parking B Entrance",
      status: "pending"
    },
    {
      id: "T5",
      agent: "Parking AI",
      title: "Signage setup for Overflow P2 Lot",
      description: "Lot C is at 92% capacity. Deploy signage guiding vehicles to open Parking Lot B slots.",
      priority: "LOW",
      eta: "8 min",
      location: "Outer Loop P2 Ring",
      status: "pending"
    }
  ]);

  const [logs, setLogs] = useState<string[]>([
    "[18:02:10] VOLUNTEER-CORE: Marshalling link SECURED.",
    "[18:03:00] TASK: Direct flow task auto-generated by Gate AI."
  ]);

  useEffect(() => {
    setIsClient(true);
    const savedToken = localStorage.getItem("fanpulse_access_token");
    const savedEmail = localStorage.getItem("fanpulse_email");
    setToken(savedToken);
    setEmail(savedEmail);
  }, []);

  const handleToggleTaskStatus = (id: string) => {
    playSuccess();
    setTasks(prev => prev.map(t => {
      if (t.id === id) {
        const newStatus = t.status === "completed" ? "pending" : "completed";
        const now = new Date().toLocaleTimeString();
        setLogs(prevLogs => [`[${now}] LOG: Task ${t.id} marked as ${newStatus.toUpperCase()}.`, ...prevLogs]);
        speakText(`Task ${t.title} marked as ${newStatus}`);
        return { ...t, status: newStatus as "pending" | "completed" };
      }
      return t;
    }));
  };

  const handleRoleSelect = (role: string) => {
    playBeep();
    setSelectedRole(role);
  };

  const handleQuickLogin = async () => {
    setLoading(true);
    try {
      await fetch(`${API_BASE}/auth/register`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ email: "volunteer@fanpulse.com", password: "Password123!", role: "volunteer" }),
      });
    } catch (e) {}

    try {
      const res = await fetch(`${API_BASE}/auth/login`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ email: "volunteer@fanpulse.com", password: "Password123!" }),
      });
      const data = await res.json();
      
      let finalData = data;
      if (data.mfa_required) {
        const mfaRes = await fetch(`${API_BASE}/auth/login`, {
          method: "POST",
          headers: { "Content-Type": "application/json" },
          body: JSON.stringify({ email: "volunteer@fanpulse.com", password: "Password123!", mfa_code: "123456" }),
        });
        finalData = await mfaRes.json();
      }

      if (finalData.access_token) {
        localStorage.setItem("fanpulse_access_token", finalData.access_token);
        localStorage.setItem("fanpulse_role", finalData.role);
        localStorage.setItem("fanpulse_email", finalData.email);
        setToken(finalData.access_token);
        setEmail(finalData.email);
      }
    } catch (err) {
      console.error(err);
    } finally {
      setLoading(false);
    }
  };

  if (!isClient) return null;

  if (!token) {
    return (
      <div className="flex-1 flex items-center justify-center p-6 relative font-sans bg-[#040508] text-white min-h-screen">
        <div className="w-full max-w-sm rounded-2xl glass-panel p-8 text-center space-y-6">
          <div className="w-12 h-12 rounded-xl bg-emerald-500/10 flex items-center justify-center text-emerald-400 mx-auto">
            <Shield size={24} />
          </div>
          <div className="space-y-1">
            <h2 className="text-xl font-bold text-white">Volunteer Intelligence Portal</h2>
            <p className="text-xs text-gray-400">Coordinate accessibility assistance, crowd navigation, and safety dispatches</p>
          </div>
          <button
            onClick={handleQuickLogin}
            disabled={loading}
            className="w-full p-3.5 rounded-xl bg-emerald-500 text-slate-900 font-bold text-sm shadow-lg shadow-emerald-500/20 hover:bg-emerald-400 transition-all cursor-pointer border-none"
          >
            {loading ? "Connecting..." : "Quick Access (Demo Mode)"}
          </button>
        </div>
      </div>
    );
  }

  // Filter tasks matching current volunteer role
  const roleKeywords: { [key: string]: string } = {
    "Gate Management": "Gate",
    "Cleaning Team": "Cleaning",
    "Medical Team": "Medical",
    "Security Team": "Security",
    "Parking Team": "Parking",
    "Hospitality Team": "Hospitality",
    "Emergency Response Team": "Emergency",
    "Accessibility Team": "Accessibility"
  };

  const activeKeyword = roleKeywords[selectedRole] || "";
  const roleTasks = tasks.filter(t => t.agent.toLowerCase().includes(activeKeyword.toLowerCase()) || activeKeyword === "");

  return (
    <div className="flex-1 flex flex-col h-full font-sans bg-[#040508] text-white min-h-screen overflow-x-hidden relative">
      {/* Header */}
      <header className="flex flex-col md:flex-row justify-between items-center px-6 py-4 border-b border-white/5 bg-slate-950/40 backdrop-blur-md gap-4 z-40">
        <div className="flex items-center gap-2">
          <div className="w-8 h-8 rounded-lg bg-emerald-500/10 flex items-center justify-center text-emerald-400">
            <Cpu size={18} />
          </div>
          <div>
            <h1 className="text-xs font-extrabold text-white tracking-wider uppercase">Volunteer Intelligence console</h1>
            <span className="text-[9px] text-emerald-400/70 font-mono tracking-wider">ACTIVE SYNC TO STADIUM ORCHESTRATOR CORES</span>
          </div>
        </div>
        <div className="flex items-center gap-3">
          <span className="text-[10px] text-gray-400 font-mono">Logged in: <strong>{email}</strong></span>
          <button
            onClick={() => {
              logoutUser();
              router.push("/");
            }}
            className="flex items-center gap-1 px-3 py-1.5 rounded-lg bg-slate-800 text-[10px] font-semibold text-gray-300 hover:bg-slate-700 transition-all cursor-pointer border-none"
          >
            <LogOut size={12} /> Exit Portal
          </button>
        </div>
      </header>

      {/* Main Grid */}
      <div className="flex-1 grid grid-cols-1 lg:grid-cols-12 gap-6 p-6">
        
        {/* Left Column: Role Selector sidebar */}
        <div className="lg:col-span-4 p-5 rounded-2xl border border-white/5 bg-slate-950/40 space-y-4 flex flex-col overflow-y-auto">
          <span className="text-xs font-bold text-gray-400 uppercase tracking-widest block flex items-center gap-1.5">
            <User size={14} className="text-emerald-400" /> Select Volunteer Sub-Role
          </span>
          <div className="space-y-1.5 flex-1">
            {[
              "Gate Management",
              "Cleaning Team",
              "Medical Team",
              "Security Team",
              "Parking Team",
              "Hospitality Team",
              "Emergency Response Team",
              "Accessibility Team"
            ].map((role) => (
              <button
                key={role}
                onClick={() => handleRoleSelect(role)}
                className={`w-full text-left p-3 rounded-xl text-xs font-bold transition-all border-none cursor-pointer flex justify-between items-center ${
                  selectedRole === role
                    ? "bg-emerald-500 text-slate-950 shadow-md shadow-emerald-500/10"
                    : "bg-slate-900/40 hover:bg-slate-900 text-gray-300"
                }`}
              >
                <span>{role}</span>
                <ChevronRight size={12} className="opacity-75" />
              </button>
            ))}
          </div>

          {/* AI Status summary */}
          <div className="p-4 bg-slate-900/60 rounded-xl border border-white/5 space-y-1 text-xxs font-mono text-gray-400">
            <span className="text-gray-500 block uppercase font-bold">System Dispatch Status</span>
            <p>Active Tasks: {tasks.filter(t => t.status === "pending").length}</p>
            <p>Resolved Tasks: {tasks.filter(t => t.status === "completed").length}</p>
            <p>Average ETA: 3.4 Minutes</p>
          </div>
        </div>

        {/* Right Column: AI tasks dashboard & logs */}
        <div className="lg:col-span-8 flex flex-col gap-6 overflow-y-auto pr-1">
          
          {/* Active Tasks list */}
          <div className="p-6 rounded-2xl border border-white/5 bg-slate-950/40 space-y-4 flex flex-col">
            <div className="flex justify-between items-center">
              <span className="text-xs font-bold text-emerald-400 uppercase tracking-widest block flex items-center gap-1.5">
                <Bell size={14} className="animate-pulse" /> Active Dispatches ({selectedRole})
              </span>
              <span className="text-[10px] text-gray-500 font-mono uppercase font-bold">AI Recommended route links included</span>
            </div>

            <div className="space-y-3 flex-1 overflow-y-auto max-h-[360px] pr-1">
              {roleTasks.length > 0 ? (
                roleTasks.map((t) => (
                  <div
                    key={t.id}
                    className={`p-4 rounded-xl border transition-all flex flex-col md:flex-row justify-between gap-4 items-start md:items-center ${
                      t.status === "completed"
                        ? "bg-slate-900/30 border-white/5 opacity-60"
                        : "bg-slate-900/60 border-white/5 hover:border-emerald-500/20"
                    }`}
                  >
                    <div className="space-y-1.5 flex-1">
                      <div className="flex flex-wrap items-center gap-2">
                        <span className="px-2 py-0.5 rounded bg-emerald-500/10 text-emerald-400 font-mono text-[9px] font-bold uppercase tracking-wider">{t.agent}</span>
                        <span className={`px-2 py-0.5 rounded text-[9px] font-mono font-bold ${
                          t.priority === "HIGH" ? "bg-red-500/10 text-red-400" : t.priority === "MEDIUM" ? "bg-amber-500/10 text-amber-400" : "bg-gray-500/10 text-gray-400"
                        }`}>{t.priority} PRIORITY</span>
                        <span className="text-[10px] text-gray-500 font-mono flex items-center gap-1"><MapPin size={10} /> {t.location}</span>
                      </div>
                      <h3 className="text-xs font-bold text-white leading-snug">{t.title}</h3>
                      <p className="text-xxs text-gray-400 leading-relaxed font-semibold">{t.description}</p>
                    </div>

                    <div className="flex md:flex-col items-end gap-3 shrink-0">
                      <div className="text-right font-mono text-xxs text-gray-500">
                        <span>ETA: <strong className="text-white">{t.eta}</strong></span>
                      </div>
                      <button
                        onClick={() => handleToggleTaskStatus(t.id)}
                        className={`px-3 py-2 rounded-lg text-xs font-bold cursor-pointer transition-all border-none flex items-center gap-1.5 ${
                          t.status === "completed"
                            ? "bg-emerald-500/10 text-emerald-400"
                            : "bg-emerald-500 text-slate-950 hover:bg-emerald-400 shadow-md"
                        }`}
                      >
                        <CheckSquare size={13} /> {t.status === "completed" ? "Completed" : "Complete Task"}
                      </button>
                    </div>
                  </div>
                ))
              ) : (
                <div className="text-center py-12 text-xxs text-gray-500 font-mono">
                  <CheckCircle size={24} className="mx-auto text-gray-700 mb-1" />
                  No tasks assigned to {selectedRole} at this time.
                </div>
              )}
            </div>
          </div>

          {/* Timeline dispatch logs */}
          <div className="p-5 rounded-2xl border border-white/5 bg-slate-950/40 space-y-3 flex-1 min-h-[150px] flex flex-col">
            <span className="text-xs font-bold text-gray-400 uppercase tracking-widest block flex items-center gap-1.5">
              <Activity size={14} className="text-gray-400" /> Operational Dispatch Timeline Logs
            </span>
            <div className="flex-1 overflow-y-auto space-y-1.5 font-mono text-[9px] text-gray-500 pr-1">
              {logs.map((log, index) => (
                <p key={index}>{log}</p>
              ))}
            </div>
          </div>

        </div>

      </div>
    </div>
  );
}
